### ISSUE TITLE
Bug: Overlay Component is not rendering 

### ISSUE THREAD

**Issue by tewarig** [react-native-elements/playground#26]
This issue seems  similar to #19 
https://react-native-elements.js.org/#/overlay
![Screenshot from 2021-03-10 22-26-28](https://user-images.githubusercontent.com/54894783/110667707-89dc9180-81f0-11eb-8d51-635bf0e91966.png)

**Comment by sachdeva-shrey** [comment]
Hey @tewarig, are you working on this issue?

**Comment by tewarig** [comment]
so... I was working on this issue. this is what my bug fix looks like.. should I go ahead with this @pranshuchittora  ?
![pr](https://user-images.githubusercontent.com/54894783/110675485-f0fe4400-81f8-11eb-950b-2d647fb9e4db.gif)

**Comment by pranshuchittora** [comment]
Can you elaborate what's the issue?

**Comment by tewarig** [comment]
currently in the playground overlay component is not rendering  (https://react-native-elements.js.org/#/overlay) 
this is what is look like
![Screenshot from 2021-03-11 21-56-30](https://user-images.githubusercontent.com/54894783/110820006-b659e180-82b4-11eb-8ea2-e029619aebc2.png)

**Comment by pranshuchittora** [comment]
Checking the `isVisible` prop in the playground shows the overlay. Hence that's the intended behaviour
