### ISSUE TITLE
Bug : bottom-sheet component is not   rendering and giving a error  No safe area insets value available. 

### ISSUE THREAD

**Issue by tewarig** [react-native-elements/playground#27]
I was going through the react-native-elements playground and found out, bottom sheet component is not rendering and it is displaying this error.
``` 
Error: No safe area insets value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app
````
https://react-native-elements.js.org/#/bottom-sheet
![Screenshot from 2021-03-10 22-34-15](https://user-images.githubusercontent.com/54894783/110668349-3880d200-81f1-11eb-8329-a137d763673e.png)

maybe this can be solved by importing SafeAreaProvider or safe area view.

**Comment by jalajcodes** [comment]
Working on it.

**Comment by pranshuchittora** [comment]
This can probably fix this -> https://github.com/react-native-elements/playground/pull/17

Feel free to reopen if this occurs, again
