### ISSUE TITLE
bug: Apparently a typo in .gitignore

### ISSUE THREAD

**Issue by iamsaumya** [react-native-elements/playground#29]
This line seems to be a typo, I am aware of the `package-lock.json` but not the `package-json.lock` file. 

https://github.com/react-native-elements/playground/blob/562107d49b6fb7e6f558396c1ca1abe3c400b39d/.gitignore#L21

Is it a specific file that npm creates? There is a possibility I don't know about it.

**Comment by iamsaumya** [comment]
Adding to that, I don't see `package-lock.json` in the codebase I believe it should be added to a git repo.

**Comment by tewarig** [comment]
well, @iamsaumya I don't think that is a typo.😅    check this.. https://github.com/nodejs/citgm/issues/451

**Comment by iamsaumya** [comment]
I see, in that case. The typo `package-json.lock` should be `package-lock.json`, Isn't it?

**Comment by iamsaumya** [comment]
I think it will better to inform the author of https://github.com/react-native-elements/playground/pull/23 to fix the typo in .gitignore as he is pushing the `lock` file to repo.

**Comment by pranshuchittora** [comment]
@iamsaumya pls open a PR with the fix :)
