### ISSUE TITLE
Feat: Adding prop explorer for AirBnB rating and all other props

### ISSUE THREAD

**Issue by Uyadav207** [react-native-elements/playground#43]
**Is your feature request related to a problem? Please Describe.**

- The props explorer for (AirBnB) is missing. 

**Describe the solution you'd like**

- Introducing `AirbnbRating.mdx`.

**Additional context**

- Please see the bottom right corner.(no options for viewing props.)

![Screenshot from 2021-03-12 12-32-30](https://user-images.githubusercontent.com/50916299/110904943-bc40d880-832f-11eb-91f2-781dffbaca2a.png)

@pranshuchittora, I would like to work on the above-mentioned issue.  Already started working on it. Please assign me the task.
Thanks :)

**Comment by Uyadav207** [comment]
I would also like to add another props explorers, is it fine?

**Attaching below the list, I will be working on: **

- `buttongroup.mdx`
- `checbox.mdx`
- `Header.mdx`
- `icon.mdx`
- `image.mdx`

For now, I think this would be enough. Maybe, later I'll be adding more contributions.

**Comment by pranshuchittora** [comment]
This seems to be similar to https://github.com/react-native-elements/playground/issues/41

**Comment by Uyadav207** [comment]
@pranshuchittora, I think the #41 is trying to add additional props and update the older ones, while I am trying to **Document**  in an markdown it.

**Comment by Uyadav207** [comment]
The explorer is no available for many components.

@pranshuchittora,

**Comment by pranshuchittora** [comment]
Yeah, go ahead. Make sure there's no open PR

**Comment by nlok5923** [comment]
@Uyadav207 it's quite a big issue so please can u let me work on `header.mdx`

**Comment by Uyadav207** [comment]
@nlok5923, Actually I have started working. but don't worry, please Go for.... `pricing.mdx`. 
👍🏿

**Comment by Uyadav207** [comment]
@pranshuchittora, can you assign me?
This will help to reduce the repetitive issues.

**Comment by nlok5923** [comment]
> @nlok5923, Actually I have started working. but don't worry, please Go for.... `pricing.mdx`.
> 👍🏿

Thanks working on `pricing.mdx`

**Comment by Uyadav207** [comment]
> Yeah, go ahead. Make sure there's no open PR

Sure, working on it.

**Comment by Uyadav207** [comment]
![Screenshot from 2021-03-13 16-47-54](https://user-images.githubusercontent.com/50916299/111028383-5716e100-841c-11eb-8881-cacaf19438ea.png)


## **Expected**


Total number of ratings to display

|  Type  | Default |
| :----: | :-----: |
| number |   5     |

---

-  `defaultRating`

Initial value for the rating defaultRating

|      Type      | Default |
| :------------: | :-----: |
|     number     |  1      |

**Comment by Uyadav207** [comment]
@pranshuchittora, How can I resolve this?
please help me out.

**Comment by Uyadav207** [comment]
> ![Screenshot from 2021-03-13 16-47-54](https://user-images.githubusercontent.com/50916299/111028383-5716e100-841c-11eb-8881-cacaf19438ea.png)
> ## **Expected**
> 
> Total number of ratings to display
> Type 	Default
> number 	5
> 
>     * `defaultRating`
> 
> 
> Initial value for the rating defaultRating
> Type 	Default
> number 	1

@pranshuchittora, sir ... How to style MDX........ DO I need to make `style modules` for MDX styling..... as MDX follows JSX. ??
