### ISSUE TITLE
PWA (manifest) logo icons are not being loaded

### ISSUE THREAD

**Issue by ankushdutt** [react-native-elements/playground#48]
**Describe the bug**

* PWA logo icons are not present

**Expected behavior**

* Logo images should be present and hosted

**To Reproduce**

* Go to https://react-native-elements.js.org/#/
* See console
![image](https://user-images.githubusercontent.com/51174480/111017383-34170d80-83d9-11eb-9218-e2b184f2fcfd.png)
* The required app logo images are not present

**Comment by tstariqul** [comment]
@ankushdutt can you assign in here

**Comment by ankushdutt** [comment]
@tstariqul This issue is already resolved in PR #49
