### ISSUE TITLE
Maintaining a11y

### ISSUE THREAD

**Issue by jugshaurya** [react-native-elements/playground#54]
**Issue main aim:**
- Accessibility plays a vital role in today's modern web world. Some a11y rules were broken
- hence require fixing.

**Problems in the webapp **
- a11y/alt-txt
- a11y/accessible-emoji
- 
**one security concern**
- react/jsx-no-target-blank

![Screenshot from 2021-03-13 19-49-24](https://user-images.githubusercontent.com/39825643/111033554-d36aed80-8437-11eb-9d62-5f24e3eb724c.png)

**Solution**
- adding span with role "img"
- adding alt attribute to img tags
- adding rel="noopener noreferrer"

**Comment by Uyadav207** [comment]
@jugshaurya already made a PR buddy. #47
