### ISSUE TITLE
Add Prop Explorer to all the components 

### ISSUE THREAD

**Issue by tewarig** [react-native-elements/playground#66]
**Is your feature request related to a problem? Please Describe.**

Currently, Prop Explorer is not available for most of the components in React Native elements. 
only Avatar, Badge, Button have a prop explorer for not. 
Airbnb Rating comp does have a PR #53  adding prop component to it. 

**Describe the solution you'd like**

We should add Prop Explorer to all of the components. This would enhance the experience of PlayGround by a lot.

**Describe alternatives you've considered**

**Additional context**

![demo](https://user-images.githubusercontent.com/54894783/111060262-8df30280-84c1-11eb-8336-2f58d295bc86.gif)

**Comment by Uyadav207** [comment]
@tewarig, buddy did with this issue day before yesterday. and made all the required changes. and you reviewed also right ?
please take some other issue 

The issue was #43

**Comment by tewarig** [comment]
> @tewarig, buddy already done with this issue day before yesterday. and made all the required changes. and you reviewed also right ?
> please take some other issue
> 
> The issue was #43

sorry i didn't this issue.
