### ISSUE TITLE
Lack of proper alignment between the Type and Default in the Props explorer

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/playground#69]
**Explain what you did (Required)**
When I open the **Props Explorer** I found that the alignment between the Types and Default is not well oriented and varies for every props. Therefore I feel it should be improved for better user experience while reading

**Expected behavior (Required)**
A better alignment between Types and Default values

**Describe the bug (Required)**
No proper alignment between the Types and Default for the Props explorer

**To Reproduce (Required)**
Click on Props explorer and it will be noticed that every prop has different/varied alignments
> We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Example:
Potential fix is we can have a table view with rows and columns having proper border.

- Steps
1. Go to 'Avatar(for example)'
2. Click on 'Props explorer on the bottom right corner'
3. Scroll down to 'To the slider'
4. See the issues as it is not uniform

**Screenshots (Required)**
![Screenshot (15)](https://user-images.githubusercontent.com/39884168/111109652-2ac8a500-8581-11eb-85b9-7f412caf481d.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react |         |

**Comment by khushal87** [comment]
@pranshuchittora Can I work on it if you find this as an relevant issue?

**Comment by Uyadav207** [comment]
👋 hey @khushal87, Please try to skim every other issue before making a new one.  This will help the maintainer as well.
This issue is similar to #43. I am working on this issue...😀 I was told by the maintainer to `make sure no new issue or PR should be similar to this (opens)`...

Can you find some other issue? There are many 😀...

**Comment by khushal87** [comment]
Okay sure. Thanks for the information
