### ISSUE TITLE
Input : Placeholder text always displaying

### ISSUE THREAD

**Issue by nirnayjain** [react-native-elements/playground#72]
![Screenshot (2)](https://user-images.githubusercontent.com/67785138/111148992-51530400-85b2-11eb-9cdd-d0ad02d4ca8b.png)
Here is the link of video pointing out the issue :- https://www.loom.com/share/1617cf3700884c14a235a6a4ef999b17
 
Visit https://react-native-elements.js.org/#/input
Go to placeholder input box
we can see there that evenafter clicking on input box under placeholder box ,the placeholder text is not disappearing.
 
Current Behaviour
 >The placeholder text is not diappearing after we start typing in the placeholder box.
 
Expected Behaviour
 >The placeholder text should disappear as soon as we start typing in it.

**Comment by nirnayjain** [comment]
I m working on these issue

**Comment by Uyadav207** [comment]
Hey! @nirnayjain, Just to ensure that are you talking about..... `THE INPUT FIELD YOU ARE WRITING` ??

**Comment by nirnayjain** [comment]
@Uyadav207 yes

**Comment by Uyadav207** [comment]
![captured (5)](https://user-images.githubusercontent.com/50916299/111152889-451d7580-85b7-11eb-901f-a1a520318da9.gif)


@nirnayjain, but as per the functionality.... The placeholder is working very fine.

**Comment by nirnayjain** [comment]
just refer to the video i have shared above @Uyadav207

**Comment by Uyadav207** [comment]
The `placeholder input field` does not require any placeholder effect..... This was for the above component...

**Comment by nirnayjain** [comment]
ok got it @Uyadav207
