### ISSUE TITLE
Make home Playground and icon 🚀 inline

### ISSUE THREAD

**Issue by tstariqul** [react-native-elements/playground#84]
Only CSS property change for it.
![h](https://user-images.githubusercontent.com/72482679/111733808-ebf95e80-88a2-11eb-9400-c908584bc0c4.png)

**Comment by AkshadK7** [comment]
Is this issue still open ? @tstariqul

**Comment by tstariqul** [comment]
@AkshadK7 yes, you can do that.

**Comment by AkshadK7** [comment]
Sure, can you Assign it to me? @tstariqul

**Comment by tstariqul** [comment]
@AkshadK7 you can give a PR in here.

**Comment by AkshadK7** [comment]
@tstariqul How do I Reproduce the Issue?  I Tried changing the Viewport but still never found it abnormal as shown above!
